import {
  protectionFilmSedanHalfFront,
  protectionFilmSedanFullFront,
  protectionFilmSedanBrightBody,
  protectionFilmSedanMatBody,
  windowFilmSedanThermal,
  windowFilmSedanWindshield,
  polishingSedanFull,
  polishingSedanExterior,
  nanoCeramicSedanFull,
  nanoCeramicSedanExterior,
  nanoCeramicSedanInterior,
  protectionFilmSUVHalfFront,
  protectionFilmSUVFullFront,
  protectionFilmSUVBrightBody,
  protectionFilmSUVMatBody,
  windowFilmSUVThermal,
  windowFilmSUVWindshield,
  polishingSUVFull,
  polishingSUVExterior,
  nanoCeramicSUVFull,
  nanoCeramicSUVExterior,
  nanoCeramicSUVInterior,
} from '@/assets';

export const services = [
  {
    id: 1,
    carType: 'SEDAN',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Half front)',
    priceBefore: 1990,
    priceAfter: 1590,
    gif: protectionFilmSedanHalfFront,
  },
  {
    id: 2,
    carType: 'SEDAN',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Full front)',
    priceBefore: 3990,
    priceAfter: 3190,
    gif: protectionFilmSedanFullFront,
  },
  {
    id: 3,
    carType: 'SEDAN',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Brigh Full Body)',
    priceBefore: 11990,
    priceAfter: 9590,
    gif: protectionFilmSedanBrightBody,
  },
  {
    id: 4,
    carType: 'SEDAN',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (MAT Full Body)',
    priceBefore: 13990,
    priceAfter: 11190,
    gif: protectionFilmSedanMatBody,
  },
  {
    id: 5,
    carType: 'SEDAN',
    serviceType: 'Window Film',
    serviceName: 'Thermal Tint',
    priceBefore: 1090,
    priceAfter: 890,
    gif: windowFilmSedanThermal,
  },
  {
    id: 6,
    carType: 'SEDAN',
    serviceType: 'Window Film',
    serviceName: 'Windshield Protection',
    priceBefore: 1090,
    priceAfter: 890,
    gif: windowFilmSedanWindshield,
  },
  {
    id: 7,
    carType: 'SEDAN',
    serviceType: 'Polishing',
    serviceName: 'Full Polishing',
    priceBefore: 990,
    priceAfter: 790,
    gif: polishingSedanFull,
  },
  {
    id: 8,
    carType: 'SEDAN',
    serviceType: 'Polishing',
    serviceName: 'Exterior Polish',
    priceBefore: 790,
    priceAfter: 590,
    gif: polishingSedanExterior,
  },
  {
    id: 9,
    carType: 'SEDAN',
    serviceType: 'Nano Ceramic',
    serviceName: 'Full Nano Cermaic',
    priceBefore: 1990,
    priceAfter: 1590,
    gif: nanoCeramicSedanFull,
  },
  {
    id: 10,
    carType: 'SEDAN',
    serviceType: 'Nano Ceramic',
    serviceName: 'Exterior Nano Cermaic',
    priceBefore: 990,
    priceAfter: 790,
    gif: nanoCeramicSedanExterior,
  },
  {
    id: 11,
    carType: 'SEDAN',
    serviceType: 'Nano Ceramic',
    serviceName: 'Interior Nano Cermaic',
    priceBefore: 1190,
    priceAfter: 990,
    gif: nanoCeramicSedanInterior,
  },
  {
    id: 12,
    carType: 'SUV',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Half front)',
    priceBefore: 2390,
    priceAfter: 1990,
    gif: protectionFilmSUVHalfFront,
  },
  {
    id: 13,
    carType: 'SUV',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Full front)',
    priceBefore: 4590,
    priceAfter: 3690,
    gif: protectionFilmSUVFullFront,
  },
  {
    id: 14,
    carType: 'SUV',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (Brigh Full Body)',
    priceBefore: 13990,
    priceAfter: 1190,
    gif: protectionFilmSUVBrightBody,
  },
  {
    id: 15,
    carType: 'SUV',
    serviceType: 'PROTECTION FILM',
    serviceName: 'Paint Protection film (MAT Full Body)',
    priceBefore: 15990,
    priceAfter: 12790,
    gif: protectionFilmSUVMatBody,
  },
  {
    id: 16,
    carType: 'SUV',
    serviceType: 'Window Film',
    serviceName: 'Thermal Tint',
    priceBefore: 1290,
    priceAfter: 1090,
    gif: windowFilmSUVThermal,
  },
  {
    id: 17,
    carType: 'SUV',
    serviceType: 'Window Film',
    serviceName: 'Windshield Protection',
    priceBefore: 1090,
    priceAfter: 890,
    gif: windowFilmSUVWindshield,
  },
  {
    id: 18,
    carType: 'SUV',
    serviceType: 'Polishing',
    serviceName: 'Full Polishing',
    priceBefore: 1090,
    priceAfter: 890,
    gif: polishingSUVFull,
  },
  {
    id: 19,
    carType: 'SUV',
    serviceType: 'Polishing',
    serviceName: 'Exterior Polish',
    priceBefore: 890,
    priceAfter: 690,
    gif: polishingSUVExterior,
  },
  {
    id: 20,
    carType: 'SUV',
    serviceType: 'Nano Ceramic',
    serviceName: 'Full Nano Cermaic',
    priceBefore: 2190,
    priceAfter: 1790,
    gif: nanoCeramicSUVFull,
  },
  {
    id: 21,
    carType: 'SUV',
    serviceType: 'Nano Ceramic',
    serviceName: 'Exterior Nano Cermaic',
    priceBefore: 1090,
    priceAfter: 890,
    gif: nanoCeramicSUVExterior,
  },
  {
    id: 22,
    carType: 'SUV',
    serviceType: 'Nano Ceramic',
    serviceName: 'Interior Nano Cermaic',
    priceBefore: 1290,
    priceAfter: 1090,
    gif: nanoCeramicSUVInterior,
  },
];

export const API_ROUTES = {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL,
  createBooking: '/api/v1/bookings',
};

export const voucherCodes = [
  {
    name: 'Voucher 1',
    type: 'percentage',
    value: 10,
    code: 'VOUCHER10',
  },
  {
    name: 'Voucher 2',
    type: 'fixed',
    value: 15,
    code: 'VOUCHER15',
  },
];
