import type { Metadata } from "next";
import { Footer } from "@/components/booking/Footer";
import { ScrollProvider } from "@/context/ScrollContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ScrollProvider>
      <div className="min-h-screen bg-gray-100">
        {children}
        <Footer />
      </div>
    </ScrollProvider>
  );
}

